version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: art-space-next:latest
    container_name: art-space-next-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      # - PORT=3000 # Default is already 3000
    restart: unless-stopped
